### ISSUE TITLE
Peak Occupancy map display not showing right data

### ISSUE THREAD

**Issue by solofoo** [MetropolitanTransportationCommission/vpp-webapp#108]
See example:
Emeryville/Project_ID = 43.  Peak occupancy for "Both" (on and off street) should be Weekday, 9am.  It is possible that the peak displayed on the map is pointing to the wrong day type (weekend?).  Not sure.  The legend displays the correct text for the day type and time, but the map display doesn't look right.  There are a couple of these.

**Comment by Keareys** [comment]
Resolved.
