### ISSUE TITLE
Public Comment: For all content pages. The site div is taller than the available space for the content.  It appears that the banner height needs to be subtracted from the div height.

### ISSUE THREAD

**Issue by MTCGIS** [MetropolitanTransportationCommission/vpp-webapp#129]
For all content pages. The site div is taller than the available space for the content.  It appears that the banner height needs to be subtracted from the div height.

**Comment by Keareys** [comment]
This also affects the quick Nav for the research pages.  Can we set the div height by subtracting the height of the banner?

**Comment by gilbertfrausto** [comment]
I thought you wanted the banner there and the content to scroll?
