### ISSUE TITLE
Public Comment: Create a Link between Map and Data using Study Areas

### ISSUE THREAD

**Issue by MTCGIS** [MetropolitanTransportationCommission/vpp-webapp#51]
Create View Map option from Parking Data page that switches page to Parking Map and zooms to selected Study Area.

**Comment by gilbertfrausto** [comment]
hold

**Comment by swothe** [comment]
In Chrome Version 44.0.2403.157, When I select a Study Area and click View Map from the Data Summary Options page, the home page is presented. If I click go back, then I see the map zoomed into the Study Area I selected.
If I select a Study Area and click View Map from the Inventory Data Options or Occupancy Data Options pages the Parking Map is correctly presented.

Also happening in Safari Version 9.0 (10601.1.56.2)

**Comment by Keareys** [comment]
Issue has been resolved.
