### ISSUE TITLE
Check Map Display symbology to ensure that data matches correctly

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/vpp-webapp#58]
Some of the data and color indicators don’t agree, see Albany Solano blocks where data says more than 50 spaces but color coded not red. E.g. Evelyn between Solano and Marin, east side. West side of Masonic Solano and Washington – 116 seems unlikely – double counted?

Lafayette – Deer Hill Road west of North Thompson - inventory showing 0 – shouldn’t be green

**Comment by ntargu** [comment]
checked values on solano, masonic ave is 116 in mxd, so no double counting
added no parking category (gray color) for inventory
