### ISSUE TITLE
Public Comment: Offstreet Parking Theme

### ISSUE THREAD

**Issue by MTCGIS** [MetropolitanTransportationCommission/vpp-webapp#76]
Ensure that the offstreet feature layer is displaying correctly for all parking themes.  Make sure that when user selects a different theme layer, the offstreet parking data updates accordingly.

**Comment by MTCGIS** [comment]
The off street parking theme does not show at all for a few locations when selecting any occupancy based themes.  Please verify that there is actually no data for some of the Study Areas.  For example the following study areas don't show facility data:
Berkeley Elmwood
Berkeley Telegraph
Berkeley Downtown
Downtown Mountain View
etc.

**Comment by ntargu** [comment]
Berkeley Elmwood
Berkeley Telegraph
Berkeley Downtown
These areas do not actually have facility occupancy data

Downtown Mountain View
This area has only some facilities with occupancy shown (less than mxd shows)
I am trying to figure out why
