### ISSUE TITLE
Set Default Content on Page

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/vpp-webapp#8]
Content should default to Project Overview.  See this link:
http://parkingpolicy.com/about/

**Comment by gilbertfrausto** [comment]
So default to the About page?

**Comment by Keareys** [comment]
Click the link and it will take you to the content that I am looking for. It is a page about policy. The content is what I need. The about page on our site still needs to get populated with content.

**Comment by Keareys** [comment]
I believe the content is Project Overview on our site.

**Comment by gilbertfrausto** [comment]
Oh ok I'll rip the content and add to the Home.html

**Comment by Keareys** [comment]
I think we may have some confusion... it should be the default text for the Research.html page. Are you in the office today?

**Comment by gilbertfrausto** [comment]
There is no confusion, there is no "project overview" link in the app.
You said you want it to default to this content, Which is their "About" page.
I'm remote today

**Comment by gilbertfrausto** [comment]
So default to this on the research page?
